### ISSUE TITLE
shared\modal_wnd\async_modal_runner.cpp(70): error C2664

### ISSUE THREAD

**Issue by aaa333000** [nmgwddj/logs-monitor#1]
win10，vs2017
logs-monitor-master\tool_kits\shared\modal_wnd\async_modal_runner.cpp(70): error C2664: “std::shared_ptr<AsyncModalRunner>::shared_ptr(std::shared_ptr<AsyncModalRunner> &&) noexcept”: 无法将参数 1 从“AsyncModalRunner *”转换为“std::nullptr_t”
logs-monitor-master\tool_kits\shared\modal_wnd\async_modal_runner.cpp(70): note: nullptr 只能转换成指针或句柄类型

**Comment by nmgwddj** [comment]
@aaa333000 https://github.com/nmgwddj/logs-monitor/commit/9a339d7a3c6d11b17d1936235765b23fc9071f37 已经修复该问题，如果你需要基于 VS2017 编译，需要更新静态库 duilib，请直接访问 nim duilib：https://github.com/netease-im/NIM_Duilib_Framework
